INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/wifi_data.json'
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/configuration.json'
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/hotspot.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:40:19] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:40:19] "[36mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 304 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/configuration.json'
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/hotspot.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:40:47] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:40:47] "[36mGET /static/css/milligram.css HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:40:47] "[36mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:41:02] "[32mPOST /configure/server HTTP/1.1[0m" 302 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/hotspot.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:41:02] "[37mGET /?feedback=Dati+server+configurati+con+successo&feedback_sheet_name=server&feedback_type=positive HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:41:03] "[36mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:41:07] "[31m[1mPOST /configure/hotspot/OFF HTTP/1.1[0m" 405 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:42:44] "[37mPOST /configure/hotspot/ON HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:43:05] "[37mPOST /configure/hotspot/OFF HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:43:17] "[33mGET /webcam-setup HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:43:34] "[37mGET /webcam-setup HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:43:34] "[36mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:44:07] "[37mGET /webcam-setup HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:44:57] "[37mGET /webcam-setup HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:44:57] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:44:57] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
ERROR:web_ui.endpoints:Exception on /preview-picture [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 106, in get_preview_endpoint
    return api.get_preview()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/api.py", line 141, in get_preview
    ["/usr/bin/raspistill", "-w", "800", "-h", "550", "-o", PREVIEW_PICTURE ])
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/raspistill': '/usr/bin/raspistill'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:44:57] "[35m[1mGET /preview-picture HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:44:57] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:44:57] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:44:58] "[33mGET /static/previews/zanzocam-preview.jpg?random=1616175898005 HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:44:58] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 47, in low_light_calibration
    calibration_flag = read_flag_file(CALIBRATION_FLAG)
TypeError: read_flag_file() missing 1 required positional argument: 'default'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:45:23] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:45:23] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:45:23] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:45:23] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:46:19] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:46:19] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:46:19] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:46:19] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:46:19] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:46:19] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:46:19] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:46:31] "[31m[1mPOST /webcam-calibration HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:46:31] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:46:31] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:46:31] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:46:31] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:32] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:32] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:32] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:32] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:32] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:32] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:33] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:33] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:34] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:34] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:34] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:34] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:34] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
ERROR:web_ui.endpoints:Exception on /configure/low-light-calibration-data [POST]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2098, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:35] "[35m[1mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:35] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:35] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:35] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:47:35] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:53] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:53] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:53] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:53] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:53] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:53] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:53] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:54] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:58] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:58] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:58] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:58] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:58] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:59] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:59] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:48:59] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:49:20] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:49:21] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:49:21] "[33mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:49:21] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:49:21] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:49:21] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:49:21] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:51:01] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 75, in low_light_calibration
    raise e
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 65, in low_light_calibration
    low_light.plot_curve_fit()
TypeError: plot_curve_fit() missing 2 required positional arguments: 'a_value' and 'b_value'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:51:01] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:51:01] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:51:01] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:51:01] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:51:01] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 75, in low_light_calibration
    raise e
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 65, in low_light_calibration
    low_light.plot_curve_fit(a_value, b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/low_light.py", line 67, in plot_curve_fit
    plt.savefig(CALIBRATION_GRAPH)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 512, in print_png
    dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/image.py", line 1611, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/PIL/Image.py", line 2161, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/static/previews/calibration_graph.png'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:53:14] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:53:14] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:53:14] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:53:14] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:53:15] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 75, in low_light_calibration
    raise e
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 65, in low_light_calibration
    low_light.plot_curve_fit(a_value, b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/low_light.py", line 67, in plot_curve_fit
    plt.savefig(CALIBRATION_GRAPH)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 512, in print_png
    dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/image.py", line 1611, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/PIL/Image.py", line 2161, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/static/previews/calibration_graph.png'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:54:26] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:54:26] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:54:26] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:54:26] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:54:26] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:root:--------------------> /static/previews/calibration_graph.png
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 75, in low_light_calibration
    raise e
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 65, in low_light_calibration
    low_light.plot_curve_fit(a_value, b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/low_light.py", line 69, in plot_curve_fit
    plt.savefig(CALIBRATION_GRAPH)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 512, in print_png
    dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/image.py", line 1611, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/PIL/Image.py", line 2161, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/static/previews/calibration_graph.png'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:55:17] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:55:17] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:55:17] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:55:17] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:55:17] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:root:--------------------> /static/previews/calibration_graph.png
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 75, in low_light_calibration
    raise e
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 65, in low_light_calibration
    low_light.plot_curve_fit(a_value, b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/low_light.py", line 69, in plot_curve_fit
    plt.savefig(CALIBRATION_GRAPH.absolute())
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 512, in print_png
    dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/image.py", line 1611, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/PIL/Image.py", line 2161, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/static/previews/calibration_graph.png'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:57:04] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:57:04] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:57:04] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:57:04] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:57:04] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:root:--------------------> /static/previews/calibration_graph.png
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 75, in low_light_calibration
    raise e
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 65, in low_light_calibration
    low_light.plot_curve_fit(a_value, b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/low_light.py", line 69, in plot_curve_fit
    plt.savefig(CALIBRATION_GRAPH.absolute())
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 512, in print_png
    dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/image.py", line 1611, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/PIL/Image.py", line 2161, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/static/previews/calibration_graph.png'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:57:29] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:57:29] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:57:29] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:57:29] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:57:29] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:root:--------------------> /static/previews/calibration_graph.png
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 75, in low_light_calibration
    raise e
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 65, in low_light_calibration
    low_light.plot_curve_fit(a_value, b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/low_light.py", line 70, in plot_curve_fit
    plt.savefig(BASE_PATH / "web_ui" / CALIBRATION_GRAPH.absolute())
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 512, in print_png
    dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/image.py", line 1611, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/PIL/Image.py", line 2161, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/static/previews/calibration_graph.png'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:59:09] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:59:09] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:59:09] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:59:09] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:59:09] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:root:--------------------> /home/s/projects/raspicam/zanzocam/zanzocam /static/previews/calibration_graph.png
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 75, in low_light_calibration
    raise e
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 65, in low_light_calibration
    low_light.plot_curve_fit(a_value, b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/low_light.py", line 70, in plot_curve_fit
    plt.savefig(BASE_PATH / "web_ui" / CALIBRATION_GRAPH.absolute())
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 512, in print_png
    dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/image.py", line 1611, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/PIL/Image.py", line 2161, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/static/previews/calibration_graph.png'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:59:59] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:59:59] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 18:59:59] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:00:00] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:00:00] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:root:--------------------> /home/s/projects/raspicam/zanzocam/zanzocam/web_ui
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 75, in low_light_calibration
    raise e
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 65, in low_light_calibration
    low_light.plot_curve_fit(a_value, b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/low_light.py", line 70, in plot_curve_fit
    plt.savefig(BASE_PATH / "web_ui" / CALIBRATION_GRAPH.absolute())
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 512, in print_png
    dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/image.py", line 1611, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/PIL/Image.py", line 2161, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/static/previews/calibration_graph.png'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:00:32] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:00:32] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:00:32] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:00:32] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:00:32] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:root:--------------------> /static/previews/calibration_graph.png
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 75, in low_light_calibration
    raise e
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 65, in low_light_calibration
    low_light.plot_curve_fit(a_value, b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/low_light.py", line 70, in plot_curve_fit
    plt.savefig(BASE_PATH / "web_ui" / CALIBRATION_GRAPH.absolute())
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/pyplot.py", line 859, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/figure.py", line 2311, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2217, in print_figure
    **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 1639, in wrapper
    return func(*args, **kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 512, in print_png
    dpi=self.figure.dpi, metadata=metadata, pil_kwargs=pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/matplotlib/image.py", line 1611, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/PIL/Image.py", line 2161, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '/static/previews/calibration_graph.png'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:01:01] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:01:01] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:01:01] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:01:01] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:01:01] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 75, in low_light_calibration
    raise e
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 72, in low_light_calibration
    b_value=b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: webcam-calibration.html
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:01:47] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:01:47] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:01:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:01:47] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 19:01:47] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:07:41] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:07:41] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:07:41] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:07:41] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:07:41] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:07:41] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:07:41] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:07:49] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 76, in low_light_calibration
    raise e
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 64, in low_light_calibration
    a_value, b_value = low_light.calculate_parameters()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/low_light.py", line 17, in calculate_parameters
    df = pd.read_csv(CALIBRATION_DATASET, header=None)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 3 fields in line 18, saw 5

INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:07:49] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:07:49] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:07:49] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:07:49] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:07:49] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 80, in low_light_calibration
    raise e
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 68, in low_light_calibration
    a_value, b_value = low_light.calculate_parameters()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/low_light.py", line 17, in calculate_parameters
    df = pd.read_csv(CALIBRATION_DATASET, header=None)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 3 fields in line 18, saw 5

INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:09:47] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:09:47] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:09:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:09:47] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:09:47] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:41] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:41] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:41] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:41] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:41] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:41] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:41] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:47] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:47] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:47] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:47] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:47] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:47] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:12:47] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:13:18] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:13:18] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:13:18] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:13:18] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:13:18] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:13:18] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:13:18] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:13:18] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:27] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:27] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:27] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:27] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:28] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:28] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:28] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:43] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:43] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:43] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:43] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:43] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:43] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:14:44] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:45] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:45] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:45] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:45] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:45] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:45] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:45] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:49] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:49] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:49] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:49] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:49] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:49] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:49] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:16:49] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:17:56] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:17:56] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:17:56] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:17:56] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:17:56] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:17:56] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:17:56] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:17:56] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:18:15] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:18:15] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:18:15] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:18:15] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:18:15] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:18:15] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:18:15] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:18:15] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
ERROR:root:no filter named 'len'
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 69, in low_light_calibration
    b_value=b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/templates/low-light-calibration.html", line 42, in template
    <textarea id="calibration-data" name="calibration-data" rows="{{ max(calibration_data|len, 20) }}">{{ calibration_data }}</textarea>
jinja2.exceptions.TemplateAssertionError: no filter named 'len'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 85, in low_light_calibration
    feedback="Qualcosa e' andato storto calcolando la curva. Verifica i dati inseriti e correggili se necessario.")
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: webcam-calibration.html
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:19:47] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:19:47] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:19:47] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:19:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:19:47] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
ERROR:root:no filter named 'len'
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 69, in low_light_calibration
    b_value=b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/templates/low-light-calibration.html", line 42, in template
    <textarea id="calibration-data" name="calibration-data" rows="{{ max(calibration_data|len, 20) }}">{{ calibration_data }}</textarea>
jinja2.exceptions.TemplateAssertionError: no filter named 'len'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 85, in low_light_calibration
    feedback="Qualcosa e' andato storto calcolando la curva. Verifica i dati inseriti e correggili se necessario.")
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: webcam-calibration.html
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:19:55] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:19:55] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:19:55] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:19:55] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:19:55] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
ERROR:root:'len' is undefined
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 69, in low_light_calibration
    b_value=b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/templates/low-light-calibration.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/templates/base.html", line 28, in top-level template code
    {% block content %}
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/templates/low-light-calibration.html", line 42, in block "content"
    <textarea id="calibration-data" name="calibration-data" rows="{{ max(len(calibration_data), 20) }}">{{ calibration_data }}</textarea>
jinja2.exceptions.UndefinedError: 'len' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 85, in low_light_calibration
    feedback="Qualcosa e' andato storto calcolando la curva. Verifica i dati inseriti e correggili se necessario.")
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: webcam-calibration.html
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:20:18] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:20:18] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:20:18] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:20:18] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:20:18] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
ERROR:root:'max' is undefined
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 69, in low_light_calibration
    b_value=b_value)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/templates/low-light-calibration.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/templates/base.html", line 28, in top-level template code
    {% block content %}
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/templates/low-light-calibration.html", line 42, in block "content"
    <textarea id="calibration-data" name="calibration-data" rows="{{ max(calibration_data|length, 20) }}">{{ calibration_data }}</textarea>
jinja2.exceptions.UndefinedError: 'max' is undefined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 85, in low_light_calibration
    feedback="Qualcosa e' andato storto calcolando la curva. Verifica i dati inseriti e correggili se necessario.")
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: webcam-calibration.html
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:20:55] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:20:55] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:20:55] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:20:55] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:20:55] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:21:57] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:21:58] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:21:58] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:21:58] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:21:58] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:21:58] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:21:58] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:22:53] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:22:53] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:22:53] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:22:53] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:22:53] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:22:53] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:22:53] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:30:11] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:30:11] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:30:12] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:30:12] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:30:12] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:30:12] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:30:12] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:13] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:13] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:13] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:13] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:13] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:13] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:13] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:24] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:24] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:24] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:24] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:24] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:24] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:24] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:30] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:31] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:31] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:31] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:31] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:31] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:31] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:31] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:44] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:44] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:44] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:44] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:44] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:44] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:44] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:44] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:59] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:59] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:59] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:59] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:59] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:59] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:59] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:32:59] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:33:41] "[33mPOST /configure/calibration/ON HTTP/1.1[0m" 404 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:33:45] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:33:45] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:33:46] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:33:46] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:33:46] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:33:46] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:33:46] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:05] "[33mPOST /configure/calibration/ON HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:10] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:10] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:10] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:10] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:10] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:10] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:13] "[37mGET /webcam-setup HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:13] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:13] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:13] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
ERROR:web_ui.endpoints:Exception on /preview-picture [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 107, in get_preview_endpoint
    return api.get_preview()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/api.py", line 141, in get_preview
    ["/usr/bin/raspistill", "-w", "800", "-h", "550", "-o", PREVIEW_PICTURE ])
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/raspistill': '/usr/bin/raspistill'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:13] "[35m[1mGET /preview-picture HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:13] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:14] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:14] "[33mGET /static/previews/zanzocam-preview.jpg?random=1616182514055 HTTP/1.1[0m" 404 -
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:16] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:16] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:16] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:16] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:16] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:16] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:16] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:35:43] "[33mPOST /configure/calibration/ON HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:37:17] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:37:17] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:37:17] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:37:17] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:37:17] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:37:17] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:37:17] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:37:27] "[33mPOST /configure/calibration/ON HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:37:42] "[33mPOST /configure/calibration/OFF HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:37:48] "[33mPOST /configure/calibration/ON HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:40:43] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:40:43] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:40:43] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:40:43] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:40:43] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:40:43] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:40:43] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:40:44] "[33mPOST /configure/calibration/OFF HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:40:49] "[33mPOST /configure/calibration/ON HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:42:03] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:42:03] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:42:03] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:42:03] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:42:03] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:42:03] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:42:03] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:42:04] "[33mPOST /configure/calibration/OFF HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:42:08] "[33mPOST /configure/calibration/ON HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:[Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/data/calibration.flag'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:03] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:03] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:03] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:03] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:03] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:03] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:03] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
ERROR:web_ui.endpoints:Exception on /configure/low-light-calibration/OFF [POST]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2109, in make_response
    rv = self.response_class(rv, status=status, headers=headers)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 187, in __init__
    self.headers = Headers(headers)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 958, in __init__
    self.extend(defaults)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 1101, in extend
    for key, value in iter_multi_items(args[0]):
ValueError: not enough values to unpack (expected 2, got 0)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:04] "[35m[1mPOST /configure/low-light-calibration/OFF HTTP/1.1[0m" 500 -
ERROR:web_ui.endpoints:Exception on /configure/low-light-calibration/ON [POST]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2109, in make_response
    rv = self.response_class(rv, status=status, headers=headers)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 187, in __init__
    self.headers = Headers(headers)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 958, in __init__
    self.extend(defaults)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/werkzeug/datastructures.py", line 1101, in extend
    for key, value in iter_multi_items(args[0]):
ValueError: not enough values to unpack (expected 2, got 0)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:08] "[35m[1mPOST /configure/low-light-calibration/ON HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:57] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:57] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:57] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:57] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:57] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:57] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:43:57] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:00] "[37mPOST /configure/low-light-calibration/OFF HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:04] "[37mPOST /configure/low-light-calibration/ON HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:09] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:09] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:09] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:09] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:09] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:09] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:09] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:11] "[37mPOST /configure/low-light-calibration/OFF HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:15] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:15] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:15] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:15] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:15] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:16] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:18] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:18] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:18] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:18] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:18] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:18] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:18] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:37] "[37mPOST /configure/low-light-calibration/ON HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:51] "[33mGET /calibrate?a=650191&b=22502 HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:51] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:51] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:51] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:44:51] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:22] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:23] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:23] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:23] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:23] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:23] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:23] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:25] "[32mGET /configure/low-light-calibrated_values?a=650191&b=22502 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:25] "[37mGET /webcam-calibration?feedback=Valori+impostati+con+successo. HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:25] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:25] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:25] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:25] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:25] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:45:25] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 51, in low_light_calibration
    old_a_value, old_b_value = _read_data_file(CALIBRATED_PARAMS, default="0,0", action=lambda d: d.read().strip(), catch_errors=True)
ValueError: too many values to unpack (expected 2)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:51:38] "[35m[1mGET /webcam-calibration?feedback=Valori+impostati+con+successo. HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:51:38] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:51:38] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:51:38] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:51:38] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 51, in low_light_calibration
    old_a_value, old_b_value = _read_data_file(CALIBRATED_PARAMS, default="0,0", action=lambda d: d.read().strip(), catch_errors=True).split(",")
ValueError: not enough values to unpack (expected 2, got 1)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:52:15] "[35m[1mGET /webcam-calibration?feedback=Valori+impostati+con+successo. HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:52:15] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:52:15] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:52:15] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:52:15] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:16] "[37mGET /webcam-calibration?feedback=Valori+impostati+con+successo. HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:16] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:16] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:16] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:16] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:16] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:16] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:31] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:31] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:31] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:31] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:31] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:31] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:31] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:54:32] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:55:28] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:55:28] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:55:28] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:55:28] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:55:28] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:55:28] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:55:28] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:56:07] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:can't multiply sequence by non-int of type 'str'
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 63, in low_light_calibration
    a_value, b_value = low_light.calculate_parameters()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/low_light.py", line 31, in calculate_parameters
    b = -(x1*y1 - x2*y2)/(x1+x2)
TypeError: can't multiply sequence by non-int of type 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 90, in low_light_calibration
    feedback="Qualcosa e' andato storto calcolando la curva. Verifica i dati inseriti e correggili se necessario.")
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/jinja2/loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: webcam-calibration.html
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:56:07] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:56:07] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:56:07] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:56:07] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:56:07] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:can't multiply sequence by non-int of type 'str'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:56:44] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:56:44] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:56:44] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:56:44] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:56:44] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:56:44] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:56:44] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:can't multiply sequence by non-int of type 'str'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:20] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:20] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:20] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:20] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:20] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:20] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:20] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:29] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:root:can't multiply sequence by non-int of type 'str'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:29] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:29] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:29] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:29] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:29] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:29] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:29] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
ERROR:root:can't multiply sequence by non-int of type 'str'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:36] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:36] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:37] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:37] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:37] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:37] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:57:37] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:can't multiply sequence by non-int of type 'str'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:27] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:27] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:27] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:27] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:27] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:27] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:27] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:33] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:33] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:33] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:33] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:33] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:33] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:35] "[37mGET /webcam-setup HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:35] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:35] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:35] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
ERROR:web_ui.endpoints:Exception on /preview-picture [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 107, in get_preview_endpoint
    return api.get_preview()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/api.py", line 141, in get_preview
    ["/usr/bin/raspistill", "-w", "800", "-h", "550", "-o", PREVIEW_PICTURE ])
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/raspistill': '/usr/bin/raspistill'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:35] "[35m[1mGET /preview-picture HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:35] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:35] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:35] "[33mGET /static/previews/zanzocam-preview.jpg?random=1616183915889 HTTP/1.1[0m" 404 -
ERROR:root:can't multiply sequence by non-int of type 'str'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:37] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:37] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:37] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:37] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:37] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:37] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:37] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:42] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:43] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:43] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:43] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:43] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:43] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:43] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:43] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:53] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:53] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:53] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:53] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:53] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:53] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:53] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:58:53] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:59:28] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:59:28] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:59:28] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:59:28] "[33mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:59:28] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:59:28] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:59:28] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:59:35] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
ERROR:web_ui.endpoints:Exception on /webcam-calibration [GET]
Traceback (most recent call last):
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/endpoints.py", line 43, in low_light_calibration_endpoint
    return pages.low_light_calibration()
  File "/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/pages.py", line 55, in low_light_calibration
    os.remove(CALIBRATION_GRAPH)  # To avoid seeing a stale one if something goes wrong
FileNotFoundError: [Errno 2] No such file or directory: '/home/s/projects/raspicam/zanzocam/zanzocam/web_ui/static/previews/calibration_graph.png'
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:59:35] "[35m[1mGET /webcam-calibration HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:59:35] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:59:35] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:59:36] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 20:59:36] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:07] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:07] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:07] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:07] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:07] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:07] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:07] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:16] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:16] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:16] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:16] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:16] "[33mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:16] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:16] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:16] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:24] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:24] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:24] "[33mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:24] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:24] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:24] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:31] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:31] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:31] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:31] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:31] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:31] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:31] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:31] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:58] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:58] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:58] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:58] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:58] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:58] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:00:58] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
ERROR:root:ufunc 'true_divide' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:02:47] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:02:47] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:02:47] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:02:47] "[33mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:02:47] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:02:48] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:02:48] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:03:24] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:03:24] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:03:24] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:03:24] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:03:24] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:03:24] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:03:24] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:26] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:26] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:26] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:26] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:26] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:26] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:26] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:38] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:38] "[37mGET /static/css/milligram.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:38] "[37mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:38] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:38] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:38] "[37mGET /static/logos/favicon.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:04:38] "[37mGET /static/fonts/raleway-v18-latin-ext_latin-regular.woff2 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:03] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:04] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:39] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:39] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:40] "[33mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:40] "[36mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:46] "[32mPOST /configure/low-light-calibration-data HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:46] "[37mGET /webcam-calibration HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:46] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:46] "[36mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:52] "[32mGET /configure/low-light-calibrated_values?a=531343&b=52737 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:52] "[37mGET /webcam-calibration?feedback=Valori+impostati+con+successo. HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:52] "[36mGET /static/logos/logo-zanzocam.png HTTP/1.1[0m" 304 -
INFO:werkzeug:127.0.0.1 - - [19/Mar/2021 21:05:52] "[37mGET /static/previews/calibration_graph.png HTTP/1.1[0m" 200 -
